export enum EProductListActionTypes {
  SET_PRODUCT_LIST_COLUMNS = "SET_PRODUCT_LIST_COLUMNS",
  SET_PRODUCT_QUANTITY = "SET_PRODUCT_QUANTITY",
  SET_SELECTED_PRODUCTS = "SET_SELECTED_PRODUCTS",
  SET_SELECTED_VARIATIONS = "SET_SELECTED_VARIATIONS",
  ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART",
  ADD_PRODUCTS_TO_CART = "ADD_PRODUCTS_TO_CART",
}
